name: vgv_coffee_app
description: Your Very Good Coffee App

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Provider for state management
  provider: ^6.0.5
  # Bloc for state management
  flutter_bloc: ^8.1.2
  bloc_test: ^9.1.1
  # Value equality
  equatable: ^2.0.5
  # Remote API
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  # System
  image_downloader: ^0.31.0
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Mocking and testing
  mocktail: ^0.3.0  
  network_image_mock: ^2.1.1
  # Lints
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true

  assets:
  - assets/background.jpeg
